name: thu_linh_thu
description: EPUB Reader
publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  file_picker: ^8.0.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path: ^1.9.0

  archive: ^3.6.1
  epubx: ^4.0.0
  flutter_html: ^3.0.0-beta.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
